server:
    port: 8080
    servlet:
        context-path: /lagikoi
spring:
    datasource:
      url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/lagikoi}
      username: ${DBMS_USERNAME:root}
      password: ${DBMS_PASSWORD:root}
jwt:
  signerKey: ${SIGNER_KEY:4/Wrj3qrBDmLcpEfv87WAt3K5EyQ1fpRC1hndgyOiLo/3ak/oTziyJzrEA2DDP1d}